
export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECT = 'GET_PROJECT';
export const NEW_PROJECT = 'NEW_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';

export const NEW_PROJECT_ERROR = 'NEW_PROJECT_ERROR';

export const SET_LOADING = 'SET_LOADING';

